robot_base_frame: base_footprint
robot_radius: 0.15
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 1.0
obstacle_range: 3.0
#mark_threshold: 1
publish_voxel_map: true
navigation_map:
  map_topic: /map
obstacles:
  observation_sources: scan
  scan:
    topic: hello_robot/scan
    data_type: LaserScan
    sensor_frame: rplidar_gpu_laser_link
    clearing: true
    marking: true
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25    
virtual_walls_map:
  map_topic: /virtual_walls/map
  use_maximum: true